### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by heavywatal** [REditorSupport/atom-language-r#13]
[Enter steps to reproduce:]

1. Return/Enter at the first line

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-language-r](https://github.com/REditorSupport/atom-language-r) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Users/watal/git/dotfiles/.atom/packages/atom-language-r/lib/r-indent.js:199

TypeError: Cannot read property 'endsWith' of undefined
    at RIndent.endsWithAssignment (/packages/atom-language-r/lib/r-indent.js:199:17)
    at RIndent.properlyIndent (/packages/atom-language-r/lib/r-indent.js:36:42)
    at HTMLElement.editorNewline (/packages/atom-language-r/lib/main.js:22:52)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:03.1.0 application:new-file (atom-pane.pane.active)
  2x -1:01.4.0 editor:newline (input.hidden-input)
  2x -1:00.5.0 core:move-up (input.hidden-input)
  2x -0:57.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:50.1.0 core:move-down (input.hidden-input)
     -0:49.7.0 core:confirm (input.hidden-input)
     -0:48.9.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.1.0 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.17 
intentions 1.1.5 
language-babel 2.84.0 
language-cmake 1.1.0 
language-latex 1.1.1 
language-markdown 0.25.1 
latex 0.49.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-stylelint 4.2.0 
linter-ui-default 1.7.1 
markdown-writer 2.7.3 
minimap 4.29.8 
pigments 0.40.2 
project-manager 3.3.5 
r-exec 0.5.0 
```

**Comment by guillaumechaumet** [comment]
line is not defined at line 1 ? in: 
`if (line.endsWith("<-")) {`

Any idea @kylebarron  ?

**Comment by guillaumechaumet** [comment]
I find a temporary solution

**Comment by heavywatal** [comment]
Confirmed the problem was solved. Thank you for the prompt response!
