### ISSUE TITLE
Failed to load a atom-language-r package grammar

### ISSUE THREAD

**Issue by laughedelic** [REditorSupport/atom-language-r#14]
Happens on load.

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-language-r](https://github.com/REditorSupport/atom-language-r) package 1.1.0

### Stack Trace

Failed to load a atom-language-r package grammar

```
At Unsupported selector 'month.abb' in /Users/laughedelic/.atom/packages/atom-language-r/grammars/tree-sitter-r.cson

TypeError: Unsupported selector 'month.abb'
    at rejectSelector (/Applications/Atom Beta.app/Contents/Resources/app/src/syntax-scope-map.js:177:15)
    at Processor.parser [as func] (/Applications/Atom Beta.app/Contents/Resources/app/src/syntax-scope-map.js:90:21)
    at Processor.process (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/postcss-selector-parser/dist/processor.js:34:20)
    at SyntaxScopeMap.addSelector (/Applications/Atom Beta.app/Contents/Resources/app/src/syntax-scope-map.js:96:14)
    at new SyntaxScopeMap (/Applications/Atom Beta.app/Contents/Resources/app/src/syntax-scope-map.js:9:18)
    at new TreeSitterGrammar (/Applications/Atom Beta.app/Contents/Resources/app/src/tree-sitter-grammar.js:38:27)
    at GrammarRegistry.createGrammar (/Applications/Atom Beta.app/Contents/Resources/app/src/grammar-registry.js:486:20)
    at CSON.readFile (/Applications/Atom Beta.app/Contents/Resources/app/src/grammar-registry.js:468:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
  at /packages/atom-language-r/grammars/tree-sitter-r.cson:1:1
```

### Non-Core Packages

<details>

```
advanced-open-file 0.16.7 
antialiased 0.1.0 
ariake-dark-syntax 0.1.3 
atom-csv-markdown 1.0.2 
atom-ide-ui 0.9.2 
atom-jade 0.3.0 
atom-language-r 1.1.0 
atom-markdown-wrapper 5.2.2 
atom-material-ui 2.1.3 
atom-sbt-client 0.2.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 2.12.2 
autoflow-diffable 0.5.0 
base16-syntax 1.8.1 
busy-signal 1.4.3 
cursor-history 0.13.1 
dash 1.7.1 
factoids 0.1.1 
file-icons 2.1.17 
file-types 0.5.5 
git-plus 7.10.0 
gl-light-syntax 3.0.0 
highlight-selected 0.13.1 
Hydrogen 2.2.3 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-flowtype 0.21.0 
ide-java 0.8.1 
ide-json 0.2.1 
ide-python 0.8.1 
ide-typescript 0.7.5 
inline-git-diff 2.3.0 
key-peek 0.2.12 
language-diff 0.7.0 
language-elm 1.5.0 
language-fish-shell 1.1.0 
language-gitignore 0.3.0 
language-haskell 1.17.3 
language-hocon 1.1.0 
language-latex 1.1.1 
language-pfm 0.82.0 
language-plantuml 0.2.0 
language-rdf 0.5.0 
language-roff 1.2.2 
language-scala 1.1.9 
language-sparql 0.3.0 
latex-completions 0.3.3 
line-diff-details 1.9.0 
linter 2.2.0 
linter-annotations 1.0.2 
linter-coffeescript 1.0.0 
linter-js-standard 5.0.0 
linter-travis-lint 1.0.0 
markdown-folder 0.5.0 
markdown-preview-enhanced 0.15.2 
markdown-table-formatter 2.9.2 
mathjax-wrapper 0.1.0 
mixed-indent-warning 0.3.0 
native-ui 0.25.2 
one-dark-vivid-syntax 1.8.0 
pen-paper-coffee-syntax 0.14.9 
pigments 0.40.2 
plain-simple 1.1.0 
plantuml-preview 0.12.9 
plist-converter 0.2.0 
pretty-json 2.0.0 
project-folder 1.5.0 
remember-folds 0.3.0 
set-syntax 0.4.0 
simple-align 0.2.0 
sort-lines 0.18.0 
standard-formatter 2.8.0 
standardjs-snippets 2.6.2 
swackets 0.35.0 
tablr 1.8.3 
teletype 0.9.0 
terminal-tab 0.5.4 
toggle 0.6.2 
trailing-spaces 0.4.0 
tree-view-autoresize 2.3.0 
vim-mode-plus 1.30.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
xml-formatter 0.11.0 
```

</details>

**Comment by guillaumechaumet** [comment]
tree-sitter-r.cson renamed to tree-sitter-r.csondev 0548345
